### PR TITLE
more typos

### PR DESCRIPTION
**Pull request by askeblad**
GhcEvents.hs
src/GHC/RTS/EventTypes.hs
src/GHC/RTS/Events.hs
src/GHC/RTS/Events/Binary.hs
src/GHC/RTS/Events/Incremental.hs
src/GHC/RTS/Events/Merge.hs
test/Roundtrip.hs

### CODE REVIEW

**Comment by askeblad** [comment]
@maoe

can you merge

**Comment by maoe** [comment]
LGTM.

I wouldn't call "eventlog" a typo though. The GHC's codebase and the user's guide use both almost interchangeably. I'm going to merge this as the distinction between the two doesn't matter much.

**Comment by askeblad** [comment]
> doesn't matter much

yes, I would agree

justification below (similar Internet search for "eventlog" returned inconsistent results)

another Organization repo contained in a comment "repocache" 

having not found consistent use of such a compound word across coding languages via an Internet search

a PR opened in that repo included among various changed lines a replacement of "repocache" with "repo cache"

**Comment by maoe** [comment]
Yeah, I agree consistent terminology is good. I just uploaded https://hackage.haskell.org/package/ghc-events-0.17.0.3.

Thanks for your contribution!

**Comment by askeblad** [comment]
> consistent terminology

in `github.com/haskell/cabal/issues/8082` (Closed) was broached English standardisation

the ghc source file `CODEOWNERS` infers collective "ownership" of certain (ghc source) subdirectores

while it might be feasible that a consensus among (ghc source) individual subdirectory codeowners

could be reached on favouring British or American English (I don't portend to represent them)

cognisant that a slight increase in the "burden' on software developers would result

concomitant with a decrease in the "burden" on proofreaders of documentation and professors

and whereas the new field proposed in the cited (cabal repo) issue was rejected

there remains the idea for an Organization repos' master 'List of Terms' (see my last comment thereon)

**Pull request merged**
