### PR TITLE
Miscellaneous updates in README.md

### PR DESCRIPTION
**Pull request by maoe**

### CODE REVIEW

**Comment by Mikolaj** [comment]
Does img.shields.io/hackage-deps work out of the box or did you need to set up anything at img.shields.io?

**Comment by maoe** [comment]
It does just work! You can check the rendered badges [here](https://github.com/maoe/ghc-events/blob/badges/README.md).

**Comment by maoe** [comment]
Ah I guess I should fill in the parens with corresponding link though. I'll make a fix.

**Comment by maoe** [comment]
Done.

**Comment by kvelicka** [comment]
Good work!

**Comment by maoe** [comment]
Thank you for reviewing this. I'm going to merge this.

**Pull request merged**
