### PR TITLE
Add support for era event types

### PR DESCRIPTION
**Pull request by fendor**
Support for Era profiling was added in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11903

### CODE REVIEW

**Comment by mpickering** [comment]
LGTM

**Comment by Mikolaj** [comment]
@maoe: if you are busy, I can review and merge

**Comment by maoe** [comment]
@Mikolaj That would be great. Thank you!

Unfortunately I don't have much time to work on open source projects these days. It'd be great if you or other maintainers could take the lead in the development.

**Comment by Mikolaj** [comment]
I'm afraid, I'm a passive maintainer as well, with a just a bit more time right now. :)

@fendor, do you know if ThreadScope copes with this change? I forgot how well it handles unknown events.

**Review by Mikolaj — APPROVED** [review]
LGTM

**Pull request merged**
