### PR TITLE
Release v0.13.0

### PR DESCRIPTION
**Pull request by maoe**
TODOs

* [x] Update ThreadScope: https://github.com/haskell/ThreadScope/pull/107
* [x] Check other reverse deps: https://packdeps.haskellers.com/reverse/ghc-events

### CODE REVIEW

**Comment by mpickering** [comment]
I was ready to update `eventlog2html` today for this change but seems like it hasn't happened yet!

**Comment by mpickering** [comment]
I updated `eventlog2html` based on the current state of master with no issues :+1:

**Comment by maoe** [comment]
Thanks for checking! I was updating ghc-events-analyze but got distracted. I’ll try to make some time to finish it up in the weekend.

**Comment by maoe** [comment]
Updated ghc-events-analyze at https://github.com/well-typed/ghc-events-analyze/compare/master...maoe:ghc-events-0.13. Some parts of the code can be improved further but I think it's good enough to release ghc-events-0.13.0 now.

**Comment by maoe** [comment]
I’ll tag and upload the new version to Hackage later.

**Comment by maoe** [comment]
Done https://hackage.haskell.org/package/ghc-events-0.13.0

**Pull request merged**
