### PR TITLE
Add support for heap profiling events

### PR DESCRIPTION
**Pull request by maoe**
This MR adds support for the new [heap profiling events support in eventlog](https://phabricator.haskell.org/D1722).

There are some points that are worth mentioning:

* `EventLogFormat.h` is updated. As in #27, we don't use the upstream version so I manually applied relevant patches from GHC.
* I chose to use `Text` instead of `String` for various text fields in the heap profiling events. Also I switched over the textual serializers from bytestring's builder to text's.
* The textual format of heap profiling events is kind of arbitrary. I'm happy to change it if anyone has a better idea.
* The code format of `heapProfParsers` looks a bit different from the other parts of the module because I'm not comfortable with the current format which causes a lot of HLint warnings.. Please let me know if it's better to make it similar.

### CODE REVIEW

**Comment by maoe** [comment]
Does anyone volunteer to review this?

**Comment by maoe** [comment]
It's been a week. I think I'll just merge this if there are no objections.

**Comment by simonmar** [comment]
Took a brief look, no objections from me.

**Comment by maoe** [comment]
Thanks! I'll merge this and release v0.7.0 when I have time today.

**Pull request merged**
