### PR TITLE
Full incremental parser, new tests.

### PR DESCRIPTION
**Pull request by kvelicka**
This PR includes a functional incremental parser for ghc-events. It also includes some new tests for `ghc-events merge`. These tests currently fail. However, they fail in the same manner when added to an unchanged version of ghc-events 0.4.4.0, so they shouldn't have been introduced by the changes introduced in this PR.

Also worth noting is the fact that the incremental parser is somewhat slower than the all-or-nothing version. Previously the library would take advantage of the fact that `EventBlock`s were in order, so one stage of mergersort could be omitted. Unfortunately, this is no longer the case since the events are read incrementally.

@Mikolaj This is the new PR, with more or less the same changes. It still appears that it cannot be merged automatically. I'm pretty confident that it can be merged manually, shouldn't be too complicated. Also, you did say that you're not the maintainer so I'll understand if you don't want to spend much time on this. In that case, could you please point me to the right person so that we could get these changes finally merged?

EDIT: Also, I would not mind to maintain the library myself, or at least perform the merge if given the necessary permissions.

### CODE REVIEW

**Comment by Mikolaj** [comment]
@kvelicka: oh, great, I will make a quick review an also test the things I promised: the advanced features needed in ThreadScope.

@simonmar: could you give Karl the permissions (or make him the maintainer)? Thank you!

**Comment by Mikolaj** [comment]
@dcoutts: could you give Karl write permissions for this repo? Thank you!

**Comment by dcoutts** [comment]
@Mikolaj @kvelicka yes that's fine by me. I don't actually have the necessary permissions to do so. It looks like it needs an owner of the haskell github org. That includes @simonmar, but it might be worth asking @hvr or someone else.

**Comment by Mikolaj** [comment]
@hvr: hi! I've just learned @dcoutts no longer has the admin rights; could you help us here and make @kvelicka a Collaborator for this repo? Thank you!

**Comment by hvr** [comment]
@Mikolaj @dcoutts  I made you "team maintainers" for ghc-events... now you should be able to manage yourself? :)

**Comment by Mikolaj** [comment]
@hvr: thank you! Now we only need to make @kvelicka a member of the Haskell organization (without this, we can't make him a team member, and only organization owners can add org members). :)

**Comment by hvr** [comment]
@Mikolaj hah... alright... I've added @kvelicka as external contributor; and I turned the `ghc-events` into an admin-group, so better not add contributors to the ghc-events team, but rather as contributors to the respective repository

**Comment by Mikolaj** [comment]
Thank you! I can now indeed add collaborators. @kvelicka: please feel free to merge and generally take care of the repos in any way you seem fit. If you can't upload to hackage, I will gladly do that. Also, please ping me, so I can perform the promised review before upload.

**Comment by kvelicka** [comment]
Thank you everyone for sorting this out.

@Mikolaj I'm ready to merge at any time now, so I'll do that right after the review. Do you know when will you have time for it?

**Comment by Mikolaj** [comment]
Hi @kvelicka! I've attempted a preliminary review of the pull request, commit by commit starting from the oldest, but in its current state, it requires some unnecessary work from me. E.g., the commit "EventParserUtils compiles but is hacky" is duplicated as "EventParserUtils compiles (hack)" and then reverted. Could you take the current master branch of the main repo and cherry-pick (`git cherry-pick <commit-hash>` or use `gitk`) all the commits from your pull request that make sense and then point me to the new branch? Another advantage of this approach is that such a branch would trivially apply as a pull request, without any conflicts. I can assist you with the git bookkeeping, if that's a problem.

**Comment by maoe** [comment]
I'm wondering what the status on this PR is. Are we going to merge this PR and modify ThreadScope or whatever depends on this library accordingly?

**Comment by kvelicka** [comment]
Hi @maoe. I've not been able to allocate much time for this over the last few months but I'd like to get this sorted and merged by the end of June since I will have much more free time then. 

Of course, I cannot guarantee much since this has slipped through the cracks many a time in the past, but it most definitely is on my TODO list. In fact, you bringing it up now shows me that there are users that would benefit from my changes and therefore finishing this merge is moving up in priority as of now.

**Comment by kvelicka** [comment]
#13 is a cleaned up version of the same PR. Closing this one down since it is now redundant.

**Pull request closed without merging**
