### PR TITLE
Introduce EVENT_TICKY_BEGIN_SAMPLE

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by maoe** [comment]
Thanks! The code looks fine to me.

Could you add a small eventlog file which contains the new event with the expected `ghc-events show` output like you did in #60?

**Comment by maoe** [comment]
Looks perfect! Thank you.

**Comment by nineonine** [comment]
@maoe Can we please push new version containing this change to hackage? We would like to use this in nofib.

**Comment by maoe** [comment]
Sure, will do later today.

**Comment by maoe** [comment]
Released https://hackage.haskell.org/package/ghc-events-0.17.0

**Comment by nineonine** [comment]
Thanks @maoe!

**Pull request merged**
