### PR TITLE
Support GHC-9.8.1

### PR DESCRIPTION
**Pull request by TeofilC**

### CODE REVIEW

**Comment by AndreasPK** [comment]
It seems the latest version on hackage builds with --allow-newer, perhaps someone could revise the bounds for the existing release?

**Comment by Mikolaj** [comment]
It's better to keep the repo and Hackage in sync. Are the bumps in the PR good enough or should they now be bumped? If they are fine, I will take the liberty of merging and revising, unless @maoe beats me to it.

**Comment by TeofilC** [comment]
`cabal update && cabal outdated` tells me things are still up-to-date

**Comment by Mikolaj** [comment]
Merged and revised.

**Pull request merged**
