### PR TITLE
Add GHC 9.10.1 to the versions tested in CI

### PR DESCRIPTION
**Pull request by BinderDavid**
I used `haskell-ci` from the current master branch of the haskell-ci repo, since the published version of haskell-ci doesn't support 9.10 yet.

### CODE REVIEW

**Comment by BinderDavid** [comment]
Hmm, the CI failure seems to be a bug in haskell-ci: The update to  `jammy` breaks older builds. I'll open an issue on the haskell-ci repo.

**Comment by BinderDavid** [comment]
@andreasabel  suggested to use his fork of `haskell-ci`. This fork uses `ghcup` for all versions of `ghc` instead of the hvr ppa. I think this is an acceptable alternative to waiting for `haskell-ci` upstream to implement a fix.

Since we don't have to fix anything for `ghc-9.10` it might also be possible to bump the upper bound on base in a metadata revision.

**Review by andreasabel — APPROVED** [review]

**Comment by BinderDavid** [comment]
@Mikolaj haskell-ci fixed this in upstream as well in https://github.com/haskell-CI/haskell-ci/pull/730 . Do you want me to refresh the CI configuration, or is this ok  for the moment?

**Review by Mikolaj — APPROVED** [review]
LGTM

**Comment by Mikolaj** [comment]
Anything else before we merge?

**Comment by BinderDavid** [comment]
No, I think this is fine. Can you do a metadata revision on Hackage to bump the upper bound on base? This would allow me to make `eventlog2html` compatible with `9.10`.

**Comment by Mikolaj** [comment]
I've done the revision. Please check in 1h if that's what you wanted and if Hackage serves it fine. Merging. Thank you!

**Pull request merged**
