### PR TITLE
new test for Eden events (smaller)

### PR DESCRIPTION
**Pull request by jberthold**
This is a smaller test for the parallel RTS events
(might also be helpful for @kvelicka as a second test file).

### CODE REVIEW

**Comment by kvelicka** [comment]
Thanks, having a smaller file would indeed be more convenient but I'd prefer to have this merged in after my changes are in - that should reduce the amount of merge conflicts.

**Comment by jberthold** [comment]
Sure, no problem - (although I don't think there would be any issue with conflicts in this patch).

**Comment by jberthold** [comment]
I should have some time this week to look into rebasing this. I cannot see just where the conflict is lurking from the Web UI but I believe it should be straightforward.
Who would be inclined to take care of merging this? @Mikolaj ?

**Comment by kvelicka** [comment]
Yep, should be fairly straightforward. My hunch is that the conflict's gonna be within the .cabal file and/or `TestVersions.hs` because they got changed after this PR was submitted. Mikolaj's currently on holiday I believe, but I'll merge the PR as soon as the conflicts are resolved.

**Comment by jberthold** [comment]
OK, this PR is now rebased (and amended to fit the new parser which sorts events by timestamp).

**Comment by kvelicka** [comment]
Everything is looking fine and behaviour appears to be the same as with the longer test, so I'm merging this.

Thanks for the PR!

**Comment by Mikolaj** [comment]
Thank you guys!

**Pull request merged**
