### PR TITLE
Removed ErrorT and some compile errors

### PR DESCRIPTION
**Pull request by kvelicka**
I removed the ErrorT instances from the code since the Get monad is able to fail itself. As a result the code behaves in an identical way but does not have deprecation warnings.
I also changed a couple of things to make sure that everything compiles error and warning free (tested on 7.8.3 and HEAD).
Lastly, I added an extra test file which is purposely cut off. This file will help to test the future incremental parser.
Apologies for a convoluted commit history, I messed it up and did not mange to clean it up.

### CODE REVIEW

**Comment by kvelicka** [comment]
@Mikolaj I'm back in action with this now. Going to review the code, fix some bugs that I remember still exist and probably set up a new PR. The main branch has had a PR merged in after I forked my version of ghc-events though. How would you advise I set mine up?

**Comment by Mikolaj** [comment]
Hi @kvelicka! Great to have you back. I'm an advocate of 'git rebase' --- just 'git fetch' rebase your branch on the new origin/master and when you push, I think, the PR should automatically update, too. If something fails, please ask.

**Comment by kvelicka** [comment]
@Mikolaj I'm fixing some remaining issues now and should finally be able to merge my changes in very soon. Sorry this got so delayed. I've just removed the mtl dependency and now only two issues have to be resolved for a working replacement - writeEventLogToFile doesn't work as of now and I'm not sure if merging works yet.

**Comment by Mikolaj** [comment]
@kvelicka: that's great news; I will try to test the advanced features that TS uses ASAP, when you issue a pull request.

**Comment by kvelicka** [comment]
@Mikolaj Hi, could we have a look at merging my changes at some point in the near future? It's a shame to have them just collect dust (and eventually bit rot) in my fork.

**Comment by Mikolaj** [comment]
I'm not the maintainer, but I will try to help. Could you create a pull request with the changes you propose to add? This old pull request is reported as "This branch has conflicts that must be resolved" for me. And please ping me --- I'm not notified when you push to branches.

**Comment by kvelicka** [comment]
Closing this pull req since GitHub doesn't allow me to open another one, plus this one's description doesn't reflect the changes anymore.

**Pull request closed without merging**
