### PR TITLE
Add support for extension to Ticky counter definition field

### PR DESCRIPTION
**Pull request by mpickering**
The ticky counter definition event now has an additional word at the end
which gives the address of the info table corresponding to that tick

GHC MR: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7525

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
LGTM

**Comment by Mikolaj** [comment]
What's needed to get this merged?

**Review by maoe — COMMENTED** [review]
I'm not a huge fan of the generous use of fromIntegral, especially the unnecessary conversion from Int64 to Int. How about something like this?

```haskell
skipExtra :: Word16 -> Get a -> Get a
skipExtra expected_size get_body = do
  bytes_read <- G.bytesRead
  res <- get_body
  bytes_read_end <- G.bytesRead
  let total_size = bytes_read_end - bytes_read
      to_skip = fromIntegral expected_size - total_size
  when (to_skip < 0) (fail "Negative to_skip")
  skip to_skip
  return res

-- | Skip extra stuff at the end of a variable sized event
--
-- For forwards compatability (allowing newer events to be read with older versions)
variableSizeParser :: Int -> (Word16 -> Int64 -> Get a) -> EventParser a
variableSizeParser event_type body_parser = do
  VariableSizeParser event_type $ do
    payloadLen <- get :: Get Word16
    bytes_read <- G.bytesRead
    skipExtra payloadLen (body_parser payloadLen (fromIntegral bytes_read))

-- | If we have already got everything then return the default value, otherwise get
--
-- For backwards compatability (to allow older events to be read with newer versions)
optionalGet
  :: Binary b
  => Word16 -- ^ Expected size
  -> Int64 -- ^ Starting byte offset
  -> b -- ^ Default value
  -> Get b
optionalGet expected_size bytes_read def = do
  bytes_read_end <- G.bytesRead
  let total_size = bytes_read_end - bytes_read
  if fromIntegral expected_size == total_size then return def else get
```

**Comment by mpickering** [comment]
I updated the MR based on the review by @maoe . Please can we merge this now.

**Comment by maoe** [comment]
Thanks. I'll take a look in a few days as I'm on a trip right now.

**Comment by maoe** [comment]
LGTM, thanks for your contribution!

**Pull request merged**
